### PR TITLE
[qt5] Rebuild for openssl3

### PR DESCRIPTION
**Pull request by h-vetinari**
Pick up patches from ubuntu, see discussion in #63 & https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3773

Closes #73 
Closes #62

### CODE REVIEW

**Comment by pkgw** [comment]
That patch didn't apply cleanly as-is because the file paths need to be prefixed with `qtbase/`. I've pushed an update to fix that.

I'm wondering if we'll need to make the patch conditional on the OpenSSL version. It's not clear to me whether that will be necessary, nor do I know off the top of my head how to implement that in the `meta.yaml`, so let's see what happens in the builds with the fixed-up patch ...

Also. it may not be relevant to our builds (it's a 32bit/64bit fix), but while we're at it we may wish to also pick up the patch [in this bug][1], which according to the discussion looks like it has also been merged upstream. Presumably it will also need its file paths munged.

[1]: https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1981807

**Comment by h-vetinari** [comment]
> That patch didn't apply cleanly as-is because the file paths need to be prefixed with `qtbase/`. I've pushed an update to fix that.

Thanks, I saw that too, and thought I'd clean up the patch situation in general a bit. However, git is taking really long to initialise a nearly 3GB single commit... 😅 

> I'm wondering if we'll need to make the patch conditional on the OpenSSL version. It's not clear to me whether that will be necessary, nor do I know off the top of my head how to implement that in the `meta.yaml`, so let's see what happens in the builds with the fixed-up patch ...

If we need to, it's very easy -- `openssl` is a variable that's known to the jinja selectors, so we can just do `# [openssl == "3"]`

> Also, it may not be relevant to our builds (it's a 32bit/64bit fix), but while we're at it we may wish to also pick up the patch [in this bug](https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1981807), which according to the discussion looks like it has also been merged upstream. Presumably it will also need its file paths munged.

I don't think it's worth the hassle to carry patches for 32bit arches, since we haven't been building those for years.

**Comment by Tobias-Fischer** [comment]
I'm not sure whether it already does what we want.

From the logs:
```
2022-11-29T16:05:22.7729708Z   OpenSSL ................................ yes
2022-11-29T16:05:22.7730062Z     Qt directly linked to OpenSSL ........ no
2022-11-29T16:05:22.7730410Z   OpenSSL 1.1 ............................ yes
...
2022-11-29T16:05:22.7908885Z Note: Overriding option 'openssl' with 'yes' (was: 'linked')
...
2022-11-29T18:04:59.7037373Z WARNING (qt-main): run-exports library package conda-forge::openssl-3.0.7-h166bdaf_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

I cannot see the linker linking in openssl3 anywhere, either.

**Comment by Tobias-Fischer** [comment]
Also note that on osx we don't use openssl at all:
https://github.com/h-vetinari/qt-main-feedstock/blob/49fb856bb77f196a3e2f16e58c515f738e2f4e04/recipe/build.sh#L241

**Comment by h-vetinari** [comment]
> I'm not sure whether it already does what we want.

Interesting... Does qt bring its own openssl? If it didn't I'd expect the builds to fail...

> ```
> 2022-11-29T16:05:22.7729708Z   OpenSSL ................................ yes
> 2022-11-29T16:05:22.7730062Z     Qt directly linked to OpenSSL ........ no
> 2022-11-29T16:05:22.7730410Z   OpenSSL 1.1 ............................ yes
> ...
> 2022-11-29T16:05:22.7908885Z Note: Overriding option 'openssl' with 'yes' (was: 'linked')
> ```

I don't have much experience with building qt; I see `build.sh` already uses:
```
configure ... \
                -openssl-linked \
                -openssl \
```
`bld.bat` OTOH uses:
```
configure ... ^
     -openssl ^
     -openssl-runtime ^
```
but this similarly warns:
```
Note: Overriding option 'openssl' with 'runtime' (was: 'yes')
```

**Comment by pkgw** [comment]
Based on the digging I've done, I think your latest commits should be doing the right thing here — the configuration options are not very intuitive! Not shocking for a such a complex piece of software.

A rerender should be able to eliminate some of the OSX matrixing, no?

**Comment by h-vetinari** [comment]
> A rerender should be able to eliminate some of the OSX matrixing, no?

I've tried, but it doesn't. I think it's the presence of the selector `# [openssl == "3"]` that prevents it.

**Comment by h-vetinari** [comment]
Couldn't even get it to collapse the osx-job with:
```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 43cd4b7..87aba02 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -29,7 +29,11 @@ source:

       # Patch for openssl 3 compatibility, picked up from ubuntu, see
       # https://git.launchpad.net/ubuntu/+source/qtbase-opensource-src/commit/?h=applied/ubuntu/devel&id=6f147c166539b23792515445beadc02fb5565d0c
+      {% if not osx %}
+      # write as jinja so smithy doesn't uselessly multiply
+      # osx builds based on seeing openssl in the selector
       - patches/0013-upstream-fixes-to-support-OpenSSL-3.0.patch        # [openssl == "3"]
+      {% endif %}

   - url: https://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_12_0_rc2.7z     # [win64]
     sha256: 2a0d2f92c60e0962ef5f6039d3793424c6f39e49ba27ac04a5b21ca4ae012e15                                      # [win64]
```

The only thing that I think would work is an explicit `skip: true  # [osx and openssl == "3"]` or hand-modifying the migrator.

**Comment by h-vetinari** [comment]
Looks like this worked (despite still showing "yes" to 1.1):
```
   OpenSSL ................................ yes
     Qt directly linked to OpenSSL ........ yes
   OpenSSL 1.1 ............................ yes
```

on linux:
```
   INFO (qt-main,lib/libQt5Network.so.5.15.6): Needed DSO lib/libssl.so.3 found in conda-forge::openssl-3.0.7-h166bdaf_0
   INFO (qt-main,lib/libQt5Network.so.5.15.6): Needed DSO lib/libcrypto.so.3 found in conda-forge::openssl-3.0.7-h166bdaf_0
```

resp. on windows:
```
   INFO (qt-main,Library/bin/Qt5Network_conda.dll): Needed DSO Library/bin/libssl-3-x64.dll found in conda-forge::openssl-3.0.7-hcfcfb64_0
   INFO (qt-main,Library/bin/Qt5Network_conda.dll): Needed DSO Library/bin/libcrypto-3-x64.dll found in conda-forge::openssl-3.0.7-hcfcfb64_0
```

**Comment by h-vetinari** [comment]
I was working to backport (forwardport?) https://github.com/conda-forge/qt-main-feedstock/pull/72/commits/2a5c64ee29129fabf3597e2844c8d2b0d88feebc to the qt6 branch, but there `-openssl-linked` is already done consistently.

**Comment by hmaarrfk** [comment]
Do you mind adding the changes from https://github.com/conda-forge/qt-main-feedstock/pull/74

I can build aarch on a multi-core x86 machines so it should finish in finite time.

**Comment by h-vetinari** [comment]
> Do you mind adding the changes from #74

WDYT about merging #74 and I rebase on that?

> I can build aarch on a multi-core x86 machines so it should finish in finite time.

Sounds great, thanks!

**Comment by hmaarrfk** [comment]
I built with 2 CPUs last night, so the build didn't finish. It can wait until things finish tonight i guess.

**Comment by h-vetinari** [comment]
> I built with 2 CPUs last night, so the build didn't finish. It can wait until things finish tonight i guess.

I meant we don't have to rebuild aarch for every PR (would be enough to do it for this one), but we could keep the PR separate from a non-aarch perspective.

In any case, I rebased and will push now (with option to rebase again if/once #74 gets merged), and you can choose which way you prefer to approach it.

**Comment by hmaarrfk** [comment]
[aarch_openssl_rebuild.zip](https://github.com/conda-forge/qt-main-feedstock/files/10132240/aarch_openssl_rebuild.zip)

```
 $ anaconda upload --user conda-forge build_artifacts/linux-aarch64/qt-main-5.15.6-h44831fa_3.conda

Using Anaconda API: https://api.anaconda.org
Using "conda-forge" as upload username
Processing 'build_artifacts/linux-aarch64/qt-main-5.15.6-h44831fa_3.conda'
Detecting file type...
File type is "Conda"
Extracting conda attributes for upload
Creating package "qt-main"
Creating release "5.15.6"
Uploading file "conda-forge/qt-main/5.15.6/linux-aarch64/qt-main-5.15.6-h44831fa_3.conda"
[ERROR] ('"qt-main" could not be found', 404)

```

hmm, seems the upload command has changed?

**Comment by h-vetinari** [comment]
@hmaarrfk 
Thanks a lot!

Did you build aarch just for OpenSSL 3 (the main point), just for 1.1.1 (would be missing the point, so I don't expect that) or both?

**Comment by hmaarrfk** [comment]
both. i also wanted topin on libsqlite instead of sqlite.

**Comment by hmaarrfk** [comment]
image

With the sed commands, the logs are about 16 MB instead of 50.

**Comment by h-vetinari** [comment]
Ah, never mind, I see the upload worked and you built both - cool! :)

**Pull request merged**
