### PR TITLE
Do not pass -DQT_REQUIRE_HOST_PATH_CHECK=OFF in cross-compiled builds

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I'm trying to build this locally now and maybe invoke CFEP03

**Comment by jschueller** [comment]
it fails because of some mirror issue, I opened https://github.com/conda-forge/conda-forge.github.io/issues/2271 for this

**Comment by hmaarrfk** [comment]
Right. But I want to get the cdt cleanup through as well so I’m trying push things forward while others chime in

**Comment by hmaarrfk** [comment]
```

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(execute())
  File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
    api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3727, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3462, in test
    environ.create_env(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1050, in create_env
    _execute_actions(prefix, precs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1338, in _execute_actions
    progressive_fetch_extract.execute()
  File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 901, in execute
    raise CondaMultiError(not_cancelled)
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-aarch64-2.17-h5b4a56d_16.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/sysroot_linux-aarch64-2.17-h5b4a56d_16.conda
  expected sha256: 55d339b2f81ff8d53043d239232cff55b45a1fbdea9fc660492afca16ba95078
  actual sha256: 0ef01e563e4943d7dff7b3adb4ba62778829f4246dffab3043e6b244996e781e

Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-aarch64-2.17-h5b4a56d_16.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/sysroot_linux-aarch64-2.17-h5b4a56d_16.conda
  expected sha256: 55d339b2f81ff8d53043d239232cff55b45a1fbdea9fc660492afca16ba95078
  actual sha256: 0ef01e563e4943d7dff7b3adb4ba62778829f4246dffab3043e6b244996e781e
```
i'm gitting a similar issue locally... so it isn't an "azure only" issue.

**Comment by hmaarrfk** [comment]
[aarch64_log.zip](https://github.com/user-attachments/files/16796739/aarch64_log.zip)

**Comment by hmaarrfk** [comment]
@jschueller how opposed are you to the circular dependency being introduced in https://github.com/conda-forge/qt-main-feedstock/pull/287 it seems to help the aarch builds.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@jschueller i would like to get one of these "no-cdts" pull requests in to help out downstream packages that experience:
https://github.com/conda-forge/opencv-feedstock/issues/401

**Pull request closed without merging**
