### PR TITLE
Add egl

### PR DESCRIPTION
**Pull request by n-elie**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by n-elie** [comment]
Looks like CDT `libglvnd-egl` is missing a link to `libEGL.so`. It includes only `libEGL.so.1` and `libEGL.so.1.1.0`
Do I need to add modify cdt_slugs.yaml to include something like what is used for `libglvnd-glx` ?
https://github.com/conda-forge/cdt-builds/blob/main/cdt_slugs.yaml#L277

**Comment by hmaarrfk** [comment]
typically the bare .so are provided in the dev packages. is there a dev package for this?

**Comment by hmaarrfk** [comment]
https://centos.pkgs.org/7/centos-x86_64/libglvnd-devel-1.0.1-0.8.git5baa1e5.el7.x86_64.rpm.html

**Comment by n-elie** [comment]
There is `mesa-libegl-devel-cos6-x86_64` which contains `libEGL.so` but `mesa-libegl-devel-cos7-x86_64` does not have it

**Comment by n-elie** [comment]
Ok, I will try to add `{{ cdt('libglvnd-devel' }}` as a build dependency

**Comment by hmaarrfk** [comment]
I would also suggest maybe adding to the configure

```
-DFEATURE_egl=ON
```

if you need the feature (intend to make this change longer lasting)

**Comment by n-elie** [comment]
This would break osx build, I need to make this conditional

**Comment by hmaarrfk** [comment]
> This would break osx build, I need to make this conditional

I understand, but these kinds of conditions are quite common for GPU related stuff.

**Comment by hmaarrfk** [comment]
"its pretty easy" to remove CDTs and not see the effects. Since this affected your other work, i do recommend affirming the desire for EGL support rather than passively enabling it.

**Comment by jschueller** [comment]
one easy way to do this is check its presence in the test section of meta.yaml:
`test -f $PREFIX/lib/qt6/plugins/platforms/libqeglfs.so  # [linux]`

**Comment by n-elie** [comment]
@jschueller I added this check. By the way, I see that there is a test for `libqxcb.so` in the recipe but the linux package does not have this file in the end?

**Comment by jschueller** [comment]
yes, that's weird, maybe its not testing anything!

**Comment by n-elie** [comment]
May `run_tests.sh` override tests from recipe?

**Comment by jschueller** [comment]
yes, thats probably it

**Comment by n-elie** [comment]
f32b9f7 Seems to be broken since a long time

**Comment by jschueller** [comment]
then we might as well set FEATURE_egl conditionally in CMAKE_ARGS, or test it in run_test.sh (also conditionaly)
but I guess FEATURE_egl will fail earlier in case something went wrong then testing it after the build

**Comment by n-elie** [comment]
https://github.com/conda/conda-build/issues/4427

**Comment by jschueller** [comment]
+1

**Review by jschueller — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Great. Thanks

**Comment by jschueller** [comment]
@n-elie @hmaarrfk  since this PR pyside6 fails its tests on aarch64 only:
```
import: 'PySide6.Qt3DAnimation'
2023-04-27T08:11:23.4804090Z Traceback (most recent call last):
2023-04-27T08:11:23.4804847Z   File "/home/conda/feedstock_root/build_artifacts/pyside6_1682581674973/test_tmp/run_test.py", line 2, in <module>
2023-04-27T08:11:23.4838232Z     import PySide6.Qt3DAnimation
2023-04-27T08:11:23.4838776Z ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
```
I compared the two feedstocks and libglvnd-devel cdt was not listed.
I tried to add this one without luck: https://github.com/conda-forge/pyside2-feedstock/pull/184
any suggestions ?

**Comment by jschueller** [comment]
maybe some dependent library is missing ? I disabled the tests for cross builds in the mean time

**Comment by bernt-matthias** [comment]
Also ran into `ImportError: libEGL.so.1: cannot open shared object file: No such file or directory` on a linux build over here:  

https://github.com/bioconda/bioconda-recipes/pull/41091 ..

**Pull request merged**
