### PR TITLE
[qt6] Rebuild for openssl3

### PR DESCRIPTION
**Pull request by h-vetinari**
Seems that #70 hasn't really helped the bot. Picking up migrations from main and #63, and exploratorily trying to remove the compiler pins on osx after https://github.com/conda-forge/qt-main-feedstock/commit/f0911622c19cc87e865bc8caad9f2dcf892ea9b5.

### CODE REVIEW

**Comment by jschueller** [comment]
thanks!

**Comment by jschueller** [comment]
I dont know if its related but now conda cannot seem to pick up 6.4.1 and errors with:
```
conda.CondaMultiError: Error with archive C:\Miniforge\pkgs\qt6-main-6.4.0-he608ae7_3.tar.bz2.
You probably need to delete and re-download or re-create this file.
Message was: failed with error: seeking backwards is not allowed
```

**Comment by jakirkham** [comment]
Maybe the download was corrupted. Perhaps try clearing the cache locally and retrying?

**Comment by jschueller** [comment]
its not locally, but on the CI: for example this one https://github.com/conda-forge/pyside2-feedstock/pull/153

**Comment by jakirkham** [comment]
Thanks for the pointer. Hmm...we've had some issues with recent `conda`, `conda-build`, and `conda-package-handling` versions. Maybe this is pointing to an issue in one of them. There are a couple bug fixes lined up for them. Idk if they will fix this issue, but that might be worth testing out once they are published

**Comment by jschueller** [comment]
ok, thanks for the heads up

**Pull request merged**
