### PR TITLE
 Do not pass -DQT_REQUIRE_HOST_PATH_CHECK=OFF in cross-compiled builds

### PR DESCRIPTION
**Pull request by traversaro**
As explained in https://github.com/conda-forge/qt-main-feedstock/issues/273#issuecomment-2202410241, the PR https://github.com/conda-forge/qt-main-feedstock/pull/274 did not actually solved https://github.com/conda-forge/qt-main-feedstock/issues/273 .

While having a proper fix would be convenient, I am not sure how to do that, so in the short term the best action is to cleanup the recipe, and continue to track the problem in https://github.com/conda-forge/qt-main-feedstock/issues/273 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
I did not bumped the build number as this is a cleanup meant to be included in the next actual build.

**Comment by hmaarrfk** [comment]
hmm, these "include in the next build" have been very hard to sync up.

**Comment by traversaro** [comment]
> hmm, these "include in the next build" have been very hard to sync up.

If prefer I can bump the build number, feel free to let me know what do you prefer.

**Comment by hmaarrfk** [comment]
yeah, just bump the build number and merge from the qt6 branch before you do. that way this fix gets in.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> yeah, just bump the build number and merge from the qt6 branch before you do. that way this fix gets in.

Done!

**Comment by hmaarrfk** [comment]
does this PR resolve #273?

**Comment by traversaro** [comment]
> does this PR resolve #273?

No, it cleans up a previous attempt to fix the issue, that did not do what was intended to do.

**Comment by traversaro** [comment]
The `aarch64` build failed for a network issue, I would like to restart just that job but I can't as only maintainer can do that I guess.

**Comment by jschueller** [comment]
restarted

**Pull request closed without merging**
