### PR TITLE
Bump to qt 5.15.9

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
[log.zip](https://github.com/conda-forge/qt-main-feedstock/files/11180479/log.zip)

**Comment by hmaarrfk** [comment]
will probably merge sunday april 9th if there aren't any comments.

**Comment by Tobias-Fischer** [comment]
Is there a matching qt-webengine to go with it so we can bump qt as well?

**Comment by hmaarrfk** [comment]
Yes, seems like it is https://github.com/conda-forge/qt-webengine-feedstock/pull/26

**Comment by traversaro** [comment]
@hmaarrfk I guess we can close this given that we packaged 5.15.15 ?

**Comment by hmaarrfk** [comment]
Yes thanks!

**Pull request closed without merging**
