### PR TITLE
Make tools, fix #25

### LINKED ISSUE #25: osx-arm64: missing qcollectiongenerator
trying to build pyside2-feedstock locally for osx_arm64 I run into this issue:

```
-- optional module Qt5XmlPatterns found (). Looked in: $PREFIX/lib/cmake/Qt5XmlPatterns
CMake Error at /Users/lo/mambaforge/conda-bld/pyside2_1652084189920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/cmake/Qt5Help/Qt5HelpConfig.cmake:14 (message):
  The imported target "Qt5::Help" references the file

     "/Users/lo/mambaforge/conda-bld/pyside2_1652084189920/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/qcollectiongenerator"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained
```

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #25 

Fix based on https://gitlab.kitware.com/utils/ci-utilities/-/merge_requests/10

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Indeed this fixes #25:
```
2022-05-10T01:32:21.1530950Z    INFO (qt-main,bin/qcollectiongenerator): Needed DSO lib/libc++.1.dylib found in conda-forge::libcxx-14.0.3-h6a5c8ee_0
2022-05-10T01:32:21.1532970Z    INFO (qt-main,bin/qcollectiongenerator): Needed DSO /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
```

**Comment by Tobias-Fischer** [comment]
This is ready for review @conda-forge/qt-main

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @Tobias-Fischer!

**Comment by ccordoba12** [comment]
Question before merging: what should we do about the aarch64 build?

@andfoy, could you take care of that?

**Comment by andfoy** [comment]
Sure, I can take care of this

**Comment by andfoy** [comment]
The issue is now open: https://github.com/conda-forge/qt-main-feedstock/issues/28

**Pull request merged**
