### PR TITLE
5.15.3 with migrations

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #21
Closes #19

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
This is somewhat ready to go. but somebody needs to build aarch.

**Comment by matthiasdiener** [comment]
> This is somewhat ready to go. but somebody needs to build aarch.

Should we build aarch on travis?

**Comment by hmaarrfk** [comment]
you are welcome to try. I just don't htink it will have enoug htime. Travis is 1hour...

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by matthiasdiener** [comment]
> you are welcome to try. I just don't htink it will have enoug htime. Travis is 1hour...

Oh, I didn't know about that limit :-(

**Comment by hmaarrfk** [comment]
Honestly, I would build locally, but I hate manually writing the correct `tee` pipe so that things run smoothly and output the log. 

Last I tried. I was able to build it out using qemu and x86-64 amchine.

**Comment by hmaarrfk** [comment]
Ok i started a local build. It might legitimately take 24 hours.

**Comment by matthiasdiener** [comment]
> Ok i started a local build. It might legitimately take 24 hours.

Do you have a script for the build that we could add to the repo?

**Comment by hmaarrfk** [comment]
```
python build-locally.py | tee aarch_log.txt
```
then select the build. Just "tee" is annoying when working on multiple manually built feedstocks.

I have a readme in pytorch https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/README.md

**Comment by hmaarrfk** [comment]
[aarch_log.zip](https://github.com/conda-forge/qt-main-feedstock/files/8562750/aarch_log.zip)

**Pull request merged**
