### PR TITLE
update recipe maintainer with linux_ppc64le manual build

### PR DESCRIPTION
**Pull request by matthiasdiener**
cc @ccordoba12

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Can i promise to fold this into one of the existing Qt merge requests in flight?

**Comment by matthiasdiener** [comment]
> Can i promise to fold this into one of the existing Qt merge requests in flight?

Sure, that's fine for me!

**Comment by hmaarrfk** [comment]
I don't think it will be that problematic. Maybe lets just merge.

**Comment by ccordoba12** [comment]
Thanks @matthiasdiener for the quick response!

**Pull request merged**
