### PR TITLE
Fix qmake with XCode 15

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See https://github.com/Homebrew/homebrew-core/pull/145729

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready for review/merge. The patch is only relevant on osx.

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/qt-main - are there any objections to merging this?
/cc @hmaarrfk

**Comment by hmaarrfk** [comment]
have you tested that this resolves your issues locally?

**Comment by Tobias-Fischer** [comment]
Yes :)

**Comment by Tobias-Fischer** [comment]
Kind reminder @conda-forge/qt-main @hmaarrfk :)

**Comment by hmaarrfk** [comment]
good on my front.

**Comment by Tobias-Fischer** [comment]
Thanks @hmaarrfk. I’ll merge tomorrow unless I hear any objections.

**Pull request merged**
