### PR TITLE
update to 5.15.4

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
can we make these logs less verbose somehow?

**Comment by hmaarrfk** [comment]
it seems like this is getting further for aarch64. i'm hoping the build will finish by morning.

**Comment by hmaarrfk** [comment]
i'm building using emulation.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
[aarch-qt-main-5.15.4.zip](https://github.com/conda-forge/qt-main-feedstock/files/8855059/aarch-qt-main-5.15.4.zip)

https://anaconda.org/mark.harfouche/qt-main/files

**Comment by hmaarrfk** [comment]
@conda-forge/qt-main this is ready for review

**Review by andfoy — APPROVED** [review]
Thanks a lot! @izahn @hmaarrfk

**Pull request merged**
