### PR TITLE
6.x: Pin clang<16

### PR DESCRIPTION
**Pull request by jschueller**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Out of interest, what's the issue with clang 16?

**Comment by jschueller** [comment]
it ends up in a build issue  in pyside

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
> it ends up in a build issue in pyside

You can ping me when you encounter it again, I'd like to know what it is and hopefully fix it (if it's due to the packaging of the compiler)

**Comment by jschueller** [comment]
I reported it to qt: https://bugreports.qt.io/browse/PYSIDE-2288

**Comment by hmaarrfk** [comment]
should we do this for 5.15.X?

**Comment by jschueller** [comment]
no, the error only shows for 6.x

**Pull request merged**
