### PR TITLE
5.15.8 - Libpq turbo

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #195
Closes #192
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
[arch_ppc_logs.zip](https://github.com/conda-forge/qt-main-feedstock/files/12777457/arch_ppc_logs.zip)

I'm really not sure what is happening with OSX + arm.

Given that this migration affects OSX+arm I need help moving this forward.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Not sure why linux would start failing now. There's no relevant [change](https://github.com/conda-forge/qt-main-feedstock/pull/199/files/072649b1a9811c8bcd190cefc5535c05f8406c31..b90fe6ed5c3c39ea26d9f59656721d3889a142f7) since 072649b1a9811c8bcd190cefc5535c05f8406c31, where CI was passing.

```
make[5]: Entering directory '$SRC_DIR/qt-build/qtbase/src/platformsupport/input/xkbcommon'
g++ -c -pipe -O2 -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wno-expansion-to-defined -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -DQT_NO_LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_XKBCOMMON_SUPPORT_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I$SRC_DIR/qtbase/src/platformsupport/input/xkbcommon -I. -I$SRC_DIR/qtbase/include -I$SRC_DIR/qtbase/include/QtXkbCommonSupport -I$SRC_DIR/qtbase/include/QtXkbCommonSupport/5.15.8 -I$SRC_DIR/qtbase/include/QtXkbCommonSupport/5.15.8/QtXkbCommonSupport -I../../../../include -I../../../../include/QtXkbCommonSupport -I$SRC_DIR/qtbase/include/QtGui/5.15.8 -I$SRC_DIR/qtbase/include/QtGui/5.15.8/QtGui -I../../../../include/QtGui/5.15.8 -I../../../../include/QtGui/5.15.8/QtGui -I$SRC_DIR/qtbase/include/QtCore/5.15.8 -I$SRC_DIR/qtbase/include/QtCore/5.15.8/QtCore -I../../../../include/QtCore/5.15.8 -I../../../../include/QtCore/5.15.8/QtCore -I$SRC_DIR/qtbase/include/QtGui -I../../../../include/QtGui -I$SRC_DIR/qtbase/include/QtCore -I../../../../include/QtCore -I.moc -I$PREFIX/include -I/usr/include/libdrm -I$PREFIX/include -I$PREFIX/include -I$SRC_DIR/qtbase/mkspecs/linux-g++ -o .obj/qxkbcommon.o $SRC_DIR/qtbase/src/platformsupport/input/xkbcommon/qxkbcommon.cpp
$SRC_DIR/qtbase/src/platformsupport/input/xkbcommon/qxkbcommon.cpp:276:16: error: 'XKB_KEY_dead_lowline' was not declared in this scope; did you mean 'XKB_KEY_dead_belowring'?
  276 |         Xkb2Qt<XKB_KEY_dead_lowline,            Qt::Key_Dead_Lowline>,
      |                ^~~~~~~~~~~~~~~~~~~~
      |                XKB_KEY_dead_belowring
$SRC_DIR/qtbase/src/platformsupport/input/xkbcommon/qxkbcommon.cpp:276:69: error: template argument 1 is invalid
  276 |         Xkb2Qt<XKB_KEY_dead_lowline,            Qt::Key_Dead_Lowline>,
      |                                                                     ^
```

**Comment by h-vetinari** [comment]
But at least osx-arm is passing now...

**Comment by hmaarrfk** [comment]
https://github.com/xkbcommon/libxkbcommon/blob/6073565903488cb5b9a8d37fdc4a7c2f9d7ad04d/NEWS#L11

**Comment by hmaarrfk** [comment]
give me a second, i'm going to patch this out, this is not worth pinning for.

**Comment by h-vetinari** [comment]
This should be good now @hmaarrfk?

**Comment by h-vetinari** [comment]
Especially as I just realized that this is (very likely) blocking everything past matplotlib in the py312 migration. 😅

**Comment by hmaarrfk** [comment]
yea.... but somebody needs to find a minute to check and upload the aarch and PPC builds. I have them completed, but I need to upload them.

**Comment by hmaarrfk** [comment]
[logs.zip](https://github.com/conda-forge/qt-main-feedstock/files/12863830/logs.zip)

**Pull request merged**
