### PR TITLE
Remove unnecessary CDTs

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
do you think that would also apply to the qt6 branch ?

**Comment by isuruf** [comment]
Yes

**Comment by hmaarrfk** [comment]
I have some questions regarding CDTs or OpenGL/X11/GTK that I added to tomorrow's agenda.

I'm going to merge https://github.com/conda-forge/qt-main-feedstock/pull/113 first, then could I push the updated to your branch? or would you prefer doing that?

**Comment by hmaarrfk** [comment]
One important difference here is that qt can no longer find EGL:

```
EGL .................................... no
```

appears in the log for linux.

**Pull request closed without merging**
