### PR TITLE
Apply patch to fix symlink generation on MacOS X

### PR DESCRIPTION
**Pull request by imikejackson**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by imikejackson** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
is there an upstream issue / PR for reference ?
you must probably edit manually the patch to insert the top project dir int the file path (qtbase ?)

**Comment by imikejackson** [comment]
https://bugreports.qt.io/browse/QTBUG-120487

**Comment by jschueller** [comment]
fine, but you should add the reference to this issue in the meta.yaml like done for the other patches

**Comment by jschueller** [comment]
done

**Pull request closed without merging**
